version: '2'
services:
  postgresql:
  container_name: postgresql
    image: registry.redhat.io/rhel8/postgresql-10:1-173.1647451846
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - env/edge-api.env
    volumes:
      - ~/dev/postgresql:/var/lib/pgsql:Z

  kafka:
    container_name: kafka
    image: quay.io/strimzi/kafka:latest-kafka-2.8.1-amd64
    restart: unless-stopped
    command:
      [
        "sh",
        "-c",
        "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $$CLUSTER_ID --ignore-formatted -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS}",
      ]
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
    volumes:
       - ~/dev/kafkadata/kraft-combined-logs:/tmp/kraft-combined-logs:Z
       - ~/dev/kafkadata/logs:/tmp/logs:Z

  kafka-ui:
    container_name: kafka-ui
    image: docker.io/provectuslabs/kafka-ui
    ports:
      - "8090:8080"
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - "kafka"
